### ISSUE TITLE
File encoding issues when running from Windows to Linux

### ISSUE THREAD

**Issue by adamalesandro** [AutoCloud/ember-cli-deploy-simply-ssh#13]
Hi there, I came across your plugin today and it does exactly what I'm looking for-simple ssh based deployment. We have a self contained Ember app not accessible to the public and so we need to upload the files to an internal web server.

I was able to get it working and all the files are present, however it appears that certain files have become corrupted or have bad encodings. So far I've noticed this with `.js` and `.css` files in `assets/` but the `index.html` is fine. Have you seen this before?

**Comment by ryedeer** [comment]
Hello Adam!

I never encountered the problem you've mentioned. However, I use a Mac as my local machine, and I currently have no Windows computer where I could try it out. I wonder if it could be related to some Windows-specific implementation of the `ssh` library or other dependencies.

If this problem is really related to this plugin itself and you find a way to fix it on Windows, we would be happy to see a PR from you.

Thank you!

**Comment by adamalesandro** [comment]
OK great, I'll dig in a little bit to see what I can find.

**Comment by adamalesandro** [comment]
So after some digging, I realized the files are actually just gzip'd on the remote machine. Running `gunzip -c vendor.js` will show the correct output. Sorry if this is a stupid question but is that the expected behavior?

**Comment by youroff** [comment]
Yes, this is indeed an expected behavior, if you use it with `ember-cli-deploy-gzip` as suggested in docs.

**Comment by adamalesandro** [comment]
I disabled the gzip plugin (which I didn't realize was being used) and now all looks good. Thanks for everyone's help.
